name: snotel_ccss_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ulmo 
  - geopandas 
  - pyarrow 
  - folium 
  - ipykernel
  - fsspec
  - mgrs
  - matplotlib-base
  - pandas
  - tqdm
  - mgrs
  - lxml
  - earthengine-api